### ISSUE TITLE
[one-size-fits-all flavor] SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by MuratOzsoyler** [cyclejs-community/create-cycle-app-flavors#10]
I have just installed create-cycle-app with one-size-fits-all flavor create an application using it. But `npm run start` command gives following error:

c:\Users\zmtemp\Desktop\geçici\js\create-cycle-2\node_modules\cycle-scripts-one-fits-all\scripts\configs\webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { const { createConfig, defineConstants, env, entryPoint, setOutput, sourceMaps, addPlugins } = require('@webpack-blocks/webpack2');
                                                                    ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (c:\Users\zmtemp\Desktop\geçici\js\create-cycle-2\node_modules\webpack\bin\convert-argv.js:96:18)
    at c:\Users\zmtemp\Desktop\geçici\js\create-cycle-2\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)

I've replaced @cycle/xstream-run with @cycle/run. Could it be something with javascript version? How can I solve this problem?

My OS is Win 10.

Thanks in advance.

**Comment by jvanbruegge** [comment]
what version of npm and node are you using?
fo you have the right dependencies of @cycle/run (new dom driver, etc)?

**Comment by MuratOzsoyler** [comment]
npm: 3.10.8
node: v4.5.0

The dependecies in package.json is as follows:
`  
        "dependencies": {
            "@cycle/dom": "^15.0.0",
            "@cycle/http": "^12.0.0",
            "@cycle/run": "^1.0.0",
            "xstream": "^10.2.0"
         },`

**Comment by MuratOzsoyler** [comment]
Inspired by your mention of node version I installed and changed to node v7+. The problem is gone. Thank you for your help.

**Comment by jvanbruegge** [comment]
Yeah, Node V4 does not support es6 destructuring, that was the problem.
