### ISSUE TITLE
[one-fits-all flavor] @cycle module depreciation warnings on app creation and a compilation error

### ISSUE THREAD

**Issue by MuratOzsoyler** [cyclejs-community/create-cycle-app-flavors#11]
After changing node v7+ I could successfully created cycle-app and webpack started.

But when creating the app these depreciation warnings appears. It seems that one-fits-all should change to new cycle unified release:
npm WARN deprecated @cycle/xstream-run@4.2.0: no longer supported. see release notes for Cycle Unified
npm WARN deprecated @cycle/base@4.2.0: no longer used. see release notes for Cycle Unified
npm WARN deprecated @cycle/xstream-adapter@3.1.0: no longer supported. see release notes for Cycle Unified

And also when app compiling this error shown:

[at-loader] src\interfaces.ts:3:27
    TS2307: Cannot find module '@cycle/dom/xstream-typings'

In order to solve these issues, after creating the app I made these changes:
1. Remove @cycle/xstream-run package
2. Install @cycle/run
3. Import `DOMSource` from `@cycle/dom` instead of  `@cycle/dom/xstream-typings` in `interfaces.ts`
4. Import `run` from `@cycle/run`

Thank you for this marvellous utility.

**Comment by jvanbruegge** [comment]
yes i will update to unified once home
