### ISSUE TITLE
How to make and "pick up" my own custom flavor?

### ISSUE THREAD

**Issue by kristianmandrup** [cyclejs-community/create-cycle-app-flavors#14]
Not really clear from the Readme. I also asked [here](https://github.com/Widdershin/cycle-scripts-widdershin/issues/1)

**Comment by jvanbruegge** [comment]
its best to just look at one flavor, ideally the one-fits-all flavor, because that was made for create-cycle-app v3. Copy it and modify it to your liking

**Comment by kristianmandrup** [comment]
And then what!? Where do I "install" it? How does the `create-cycle-app` CLI pick up my flavor?

**Comment by kristianmandrup** [comment]
Looking deep into the [code](https://github.com/cyclejs-community/create-cycle-app/blob/master/packages/create-cycle-app/src/installScripts.js)

```js
module.exports = function installScripts (appFolder, appName, flavor, verbose) {
  const originalDirectory = process.cwd()
  // ...
  const local = /^\.\/|^\//.test(flavor)
  // ...

  const args = [
    'install',
    verbose && '--verbose',
    '--save-dev',
    '--save-exact',
    local ? path.resolve(originalDirectory, flavor) : flavor
  ].filter(function (a) { return a })

  // Trigger npm installation
  const proc = spawn('npm', args, {stdio: 'inherit'})
```

So it either uses a flavor that comes with `create-cycle-app` or a local one if `flavor` value is prefixed with `./` I think? Then it installs that flavor via npm?

**Comment by jvanbruegge** [comment]
yes, either the package name of an npm package or a path in the file system, either with `./` for relative or `/` for absolute path

**Comment by kristianmandrup** [comment]
OK, could be made more clear. I was banging my head trying to understand how I was supposed to "install" a flavor. So in this project, you have published each folder in the packages I imagine?
Could be nice to somehow list all available packages that share a `"cycle-app-flavor"` keyword.

**Comment by kristianmandrup** [comment]
I'm really happy to find [webpack-blocks](https://github.com/andywer/webpack-blocks) that I see you've used for the latest flavor! Wow :)

**Comment by jvanbruegge** [comment]
I created the typescript and ts-lint block basicly for this flavor :)

**Comment by kristianmandrup** [comment]
@jvanbruegge 

How would I add [babel-plugin-transform-custom-element-classes](https://www.npmjs.com/package/babel-plugin-transform-custom-element-classes) to webpack-blocks config? Would I need to create my own block!? It's just a plugin option for the babel loader...

I wanna try to integrate custom elements v1 for use in my Cycle app :)

[custom-elements-v1-vs-js-frameworks](https://ferdychristant.com/custom-elements-v1-vs-js-frameworks-e086638cd1a9#.csh0br49h)

Cheers!

**Comment by kristianmandrup** [comment]
Ah, I think I found it [here](https://www.npmjs.com/package/@webpack-blocks/babel6)

```js
const { createConfig } = require('@webpack-blocks/webpack')
const babel = require('@webpack-blocks/babel6')
 
module.exports = createConfig([
  babel(/* options */)
])
```

`plugins (optional)`

Array of Babel plugins to use. Babel will read them from `.babelrc` or `package.json` if omitted

**Comment by kristianmandrup** [comment]
FYI [how to use babel block with options](https://github.com/andywer/webpack-blocks/blob/master/packages/babel6/__tests__/babel6.test.js#L21)

**Comment by jvanbruegge** [comment]
check out scripts/init.js
there is the babelrc generated

**Comment by kristianmandrup** [comment]
Nice :) I'm trying with this in `init.js` then... 
What is effect of `modules: false` on `es2015`?

Instead of `es2015-native-modules` please use `es2015` with `{ "modules": false }` option.
Since ES2015 modules are not supported in the browser I guess?

```js
  appPackage.babel = {
    presets: [
        ['es2015', { 'modules': false }]
    ],
    plugins: [
        'transform-custom-element-classes',
        'transform-es2015-classes',
        'syntax-jsx',
        [
          'transform-react-jsx',
          { pragma: 'snabb.html' }
        ]
    ]
  }
```

**Comment by jvanbruegge** [comment]
webpack handles the bundling and it can only do tree shaking with es6 modules. After the build they are gone

**Comment by jvanbruegge** [comment]
I just updated my flavor, so you might want to use the updated version as a base for yours
