### ISSUE TITLE
Need ability to configure dev server without ejecting cycle-scripts-one-fits-all

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#18]
I want to add options to the webserver without ejecting.
As far as I can tell that requires editing the config in node_modules :(

Or is there another way to add config? I'm unable to find one.

This could actually be a more general issue of need to specify webpack config options with out eject. 
How about looking for and merging our own config file with that in the flavour? Ideally we would not use blocks.

**Comment by SteveALee** [comment]
An alternative would be to allow us to define command line options for launching webpacker-dev-server

**Comment by jvanbruegge** [comment]
What I can do is to merge the flavor config with a local one. You would then define the config for the dev server yourself and it would be integrated in the existing one.

**Comment by SteveALee** [comment]
Great. Should be ok especially as you only set the port.

**Comment by jvanbruegge** [comment]
thats not an issue, if you would specify anything that was specified before, the previous value would be overwritten.

**Comment by SteveALee** [comment]
I just noticed that webpack supports 3 styles of config: object, promise or array. I don't think you need to support them all, just object. 

But if you wanted to could pull the flavour export into the local config file and merge there, letting local export what ever style they want. In other words you sinple import form the local config file, which in turn imports your flavour default. I think that could work if a tad convoluted

**Comment by jvanbruegge** [comment]
no, I think object is the normal and advertised way of configuring,
Im currently working on this

**Comment by SteveALee** [comment]
I'm happy with that.

Here's the [link I missed out](https://webpack.js.org/configuration/configuration-types/)
