### ISSUE TITLE
[cycle-scripts-one-fits-all] Testing with cycle-time and properties is awesome

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#19]
@jvanbruegge  I just looked at [app.tests.ts](https://github.com/cyclejs-community/create-cycle-app-flavors/blob/master/packages/cycle-scripts-one-fits-all/template/test/app.test.ts) and felt the need to gush.

I'm new to property driven testing but it makes a lot of sense. Even ignoring that, the test a beautiful!

One thing with property driven testing you rely on enough test to run to cover the edge cases, rather than writing  explicit test. Does that really happen? Also what defines how many diagrams to run, I see it takes 5Secs

The cycle community is really pulling together to produce great work!

(The only tweak I might eventually make is changing to node-tap from mocha)

**Comment by jvanbruegge** [comment]
Check the coverage, pretty unlikely to have edge cases there. But you can increase the amount of tests in a CI environment
I would suggest you wait until the recording of my talk at cycleconf will be online, I explain everything in depth there

**Comment by SteveALee** [comment]
I can't wait. The jsveryfy docs are dense and not a beginners guide. 
Please do announce it on this issue if you don't mind my leaving it open?

You can of course always add manual tests with cycle-time as well.

Is it possible to print the marble diagrams - just because! :)

**Comment by jvanbruegge** [comment]
@raquelxmoss was working on that, see https://github.com/cyclejs/time/tree/svg-from-diagram
Dont know the current status there though

**Comment by SteveALee** [comment]
interesting - though I was was think of console output - ASCII Marbles

**Comment by jvanbruegge** [comment]
you can print the diagrams that are generated, sure. I don't know of a way to do it with other streams though

**Comment by SteveALee** [comment]
Ah, yes. I was thinking of getting from Time which si not possible

**Comment by SteveALee** [comment]
That's fun to see!

They do seem a bit 'sparse in terms of number of events per diagram. But I'm sure that's OK. Perhaps even realistic of human interaction

**Comment by jvanbruegge** [comment]
You can increase the number of events by increasing the size option.

**Comment by SteveALee** [comment]
That seemed to effect the max length of the areas. Not the number of events in each. Ireally you could config no.

**Comment by jvanbruegge** [comment]
it does, but only logaritmic. I will make a PR for jsverify to make it linear

**Comment by Widdershin** [comment]
FYI the only reason it takes 5 seconds is because html-looks-like takes like 300ms, because JSDom is slow.

@raquelxmoss is working on [snabbdom-looks-like](github.com/raquelxmoss/snabbdom-looks-like), which should be much faster. Each test should only take around 2-3ms with that approach.

**Comment by jvanbruegge** [comment]
that's cool!!
But the current setup was flawed too, this PR will bring the testing time from 18s to 5s of webpack compile time

**Comment by jvanbruegge** [comment]
My talk is now online: https://vimeo.com/217133774
yay 🎉

**Comment by SteveALee** [comment]
It seems I can close this now?
