### ISSUE TITLE
[cycle-scripts-one-fits-all] New typescript 2.3.1 --strict option cause errors

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#21]
On a whim I tried the new 2,3,1 --strict option and quite a few errors are generated. These are caused by strictNullChecks and noImplicitAny being true.

I'm not suggesting we supply --strict as that will likely be too much for many devs (though typescript team recommend the settings). Rather the code should compile OK with --strict set.

A few look easy to fix but the definition of sources and run `(sources: Sources) => FantasySinks<Sinks>'.
` looks more complex.

```
ERROR in [at-loader] ./src/app.tsx:19:43
    TS7024: Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

ERROR in [at-loader] ./src/app.tsx:22:16
    TS7006: Parameter 'state' implicitly has an 'any' type.

ERROR in [at-loader] ./src/app.tsx:22:16
    TS7024: Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

ERROR in [at-loader] ./src/app.tsx:25:16
    TS7006: Parameter 'state' implicitly has an 'any' type.

ERROR in [at-loader] ./src/app.tsx:25:16
    TS7024: Function implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

ERROR in [at-loader] ./src/app.tsx:35:13
    TS2602: JSX element implicitly has type 'any' because the global type 'JSX.Element' does not exist.

ERROR in [at-loader] ./src/app.tsx:35:13
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:36:17
    TS2602: JSX element implicitly has type 'any' because the global type 'JSX.Element' does not exist.

ERROR in [at-loader] ./src/app.tsx:36:17
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:36:44
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:37:17
    TS2602: JSX element implicitly has type 'any' because the global type 'JSX.Element' does not exist.

ERROR in [at-loader] ./src/app.tsx:37:17
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:37:46
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:38:17
    TS2602: JSX element implicitly has type 'any' because the global type 'JSX.Element' does not exist.

ERROR in [at-loader] ./src/app.tsx:38:17
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:38:63
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:39:17
    TS2602: JSX element implicitly has type 'any' because the global type 'JSX.Element' does not exist.

ERROR in [at-loader] ./src/app.tsx:39:17
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:39:68
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/app.tsx:40:13
    TS7026: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

ERROR in [at-loader] ./src/index.ts:18:5
    TS2345: Argument of type 'Component' is not assignable to parameter of type '(sources: Sources) => FantasySinks<Sinks>'.
  Type 'Sinks' is not assignable to type 'FantasySinks<Sinks>'.
    Types of property 'DOM' are incompatible.
      Type 'Stream<VNode> | undefined' is not assignable to type 'FantasyObservable'.
        Type 'undefined' is not assignable to type 'FantasyObservable'.

ERROR in [at-loader] ./test/app.test.ts:23:26
    TS7006: Parameter 'count' implicitly has an 'any' type.

ERROR in [at-loader] ./test/app.test.ts:48:27
    TS2532: Object is possibly 'undefined'.
```

**Comment by jvanbruegge** [comment]
It's exactly the other way round. The fantasy error is easier, the JSX errors are the problem, because we dont have a snabbdom JSX typings

**Comment by SteveALee** [comment]
ah, I thought a couple of 'any's would do the trick

**Comment by dennari** [comment]
Ran into this as well. In my experience, when a project gets bigger, `noImplicitAny` and `strictNullChecks` are super useful and IMHO the `strict` compilerOption should be enabled by default.

In any case, it would be great to get the TSX typings working. To me, that's one of the key value proposals for using TSX. Any ideas on how this could be advanced?

**Comment by dennari** [comment]
When we're at it, I'd also consider setting
```json
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "forceConsistentCasingInFileNames": true
```

**Comment by SteveALee** [comment]
I also like to be strict as possible and recommend it, but this is 'one size fits all` and it's likely people new to type script won't want the same strictness.

That, said the supplied source and config is really a template 'suggestion' which can be modified. If we take that route we should provide docs, or an alt tsconfig. Or even a `--strict` option to the flavour.

On another point , the description says ES6 is supported as well as TS. How is that? It' not shown with the included source. Perhaps we need to add the `AllowJs` TS option?

Oh I usually also set these
`
--noFallthroughCasesInSwitch
--noImplicitReturns
--noImplicitThis
`

**Comment by SteveALee** [comment]
> In any case, it would be great to get the TSX typings working. To me, that's one of the key value proposals for using TSX. Any ideas on how this could be advanced?

So I don't really understand all the ins and outs but from scanning the [TSX support docs](https://www.typescriptlang.org/docs/handbook/jsx.html) we'd need to

* keep `jsx: preserve`
* if the problem is only the type of JSX expression being `any` we can customize the type by specifying the `JSX.Element` interface. 
* define `jsxFactory` as the snabbdom version of CreateElement() (h()?)
* provide an interface `JSX.IntrinsicElements` listing all the intrinsic snabbdom elements
* use [ReactTypings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react) as a reference

Support for Custom elements looks fairly advanced and requires understanding by developer.
* tell users to use the Capital first convention for custom elements
* ...

**Comment by jvanbruegge** [comment]
The problem is only `JSX.IntrinsicElement` that is missing a definition.
The factory is `snabbdom-pragma`
ES6 works, because typescript does not handlr module resolution, webpack does. webpack sends typescript files to tsc and js files to babel

**Comment by SteveALee** [comment]
> ES6 works, because typescript does not handlr module resolution, webpack does. webpack sends typescript files to tsc and js files to babel

Ah. Of course. :)

With the latest release of TS you can add comments in JS files to enable type checking. That would require TS to process the JS files though. Just a thought, not a suggestion.
