### ISSUE TITLE
Ejected scripts fail on Windows cmd

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#22]
When you `eject` the 3 npm scripts `start`, `test` and `build` are not portable to Windows cmd

https://github.com/cyclejs-community/create-cycle-app-flavors/blob/master/packages/cycle-scripts-one-fits-all/scripts/eject.js#L15-L17

the `NODE_ENV=development ` prefix is bash (etc) specific

I suggest using the `cross-env` package, Install it and simply prefix each existing script with `cross-env `, like so

```sh
start: 'cross-env NODE_ENV=development webpack --config webpack.config.js',
test: 'cross-env NODE_ENV=test nyc mocha-webpack --timeout=100000 --colors --webpack-config webpack.config.test.js test/**/*.test.*',
build: 'cross-env NODE_ENV=production webpack --config webpack.config.js'
```

If you agree I'll submit a PR

**Comment by SteveALee** [comment]
A more serious problem though is while NODE_ENV is correctly set the env function in the webpack-config.js is failing

the dev server is never run even with NODE_ENV=development

Could this be a problem with webpack-blocks on WIndows. Hard to guess what as the doc says it uses process.env.NODE_ENV which I logged and is getting set.

Also even if I don;t set Node_Env it doesn't work as if set to development as the docs say.

I have to edit my config so i can dev

**Comment by SteveALee** [comment]
More info - the dev server works fine if not ejected. So it seems a problem with the webpack config file when ejected. 

Does it work ok on linux?

Even when I to remove the env() from the config the server fails to start - of even appear in the output

**Comment by SteveALee** [comment]
@jvanbruegge This is the one-size-fit-all flavour

**Comment by SteveALee** [comment]
So my conclusion is dev-server2 webpac-block is failing on windows

I changed my webpack config to be like this and the server is not run

```js
    addPlugins([
        new HtmlWebpackPlugin({
            template: './index.ejs',
            inject: true,
            favicon: 'public/favicon.png',
            hash: true
        }),
        new webpack.ProvidePlugin({
            Snabbdom: 'snabbdom-pragma'
        })
    ]),
        devServer(),
        devServer.proxy({
            '/api': { target: 'http://localhost:3000' }
        }),
        sourceMaps(),
    env('production', [
        addPlugins([
            new BabiliPlugin(),
            new CopyWebpackPlugin([{ from: 'public', to: '' }])
        ])
    ])
```

**Comment by SteveALee** [comment]
info 

```
 devServer:
   { proxy: { '/api': [Object] },
     hot: true,
     historyApiFallback: true,
     inline: true },
  devtool: 'cheap-module-source-map' }
```

**Comment by SteveALee** [comment]
!!! ding !!!

run `webpack-dev-server` NOT `webpack`

``` js
"start": "cross-env NODE_ENV=development webpack-dev-server --config webpack.config.js",
```

do you want a PR?

**Comment by jvanbruegge** [comment]
yes, please
