### ISSUE TITLE
[cycle-scripts-one-fits-all] request for doc on TS + Babel

### ISSUE THREAD

**Issue by kylecordes** [cyclejs-community/create-cycle-app-flavors#26]
This flavor's README says:

> ES6 or Typescript 2.1 configured with:
>  * TypeScript target: ES6 transpiles to ES6 with lib: DOM,ES6,DOM.Iterable,ScriptHost and piped through Babel
>  * Babel targets ES5 with ES2015 preset

This (obviously) works, but can be quite surprising to someone coming in from other TypeScript use. TypeScript can compile most ES2015 (and many beyond) to ES5 nowadays, without any help from Babel. Babel adds time and (very) numerous dependencies. I assume this is needed, but haven't been able to find a reason why yet.

How about a sentence or two in the README about *why* TS+Babel?

(If someone wants to just write a sentence here, I am happy tidy up the words and make a doc PR.)

**Comment by jvanbruegge** [comment]
The main reason was JSX, but this would work now with typescript 2.2
Does Typescript has async/await yet?

**Comment by kylecordes** [comment]
Yes, async/await, including compilation back to ES5 or ES3, arrived in TypeScript 2.1. 

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html

**Comment by SteveALee** [comment]
I agree, If babel can be removed I think that would be good.

The thing I always find confusing is what exactly TS will transpile and what it won't. It certainly strips all the type stuff but apparently somethings can't be transpiled and need polyfils.

This doesn't appear to be well documented. From recent investigation I think the only issues are:

* You will want to set `--downlevelIteration` to support ES2015 iterators and `Symbol.asyncIterator` is needed at runtime for async interators 
* A ECMAScript-compliant Promise implementation must be around at runtime - this used to be the case.

Somewhat related is having the little helper functions potentially emitted in every JS file may be cleaned by webpack tree shaking. but you can include the tlslib package and use `--importHelpers`. I'm not sure if treeshaking requires ES6 modules though?

**Comment by SteveALee** [comment]
Another point is now TS is handling the JS files (allowJS) I assume it could down compile JS to ES5 too as specified by `target` 

Again not so well documented.

**Comment by jvanbruegge** [comment]
I think Babel can be dropped, this might speed up builds a bit.

**Comment by jvanbruegge** [comment]
There might be one disadvantage though. Typescript can only go full ES5, babel can transpile as much as you want with the env plugin. I don't know if this is a problem. I personally transpile always to ES5

**Comment by SteveALee** [comment]
> typescript can only go full ES5, babel can transpile as much as you want 

Can you please explain that as I don't follow. Thanks

**Comment by jvanbruegge** [comment]
Some browsers support part of ES6 natively. So if you are building for anewer version of browsers like Chrome or Firefox exclusively, you can limit the transpile step to the stuff that is not yet supported natively. E.g. they both understand arrow functions and array spread.
ES6 is a bit shorter than ES5, so you might save bytes by not transpiling

**Comment by jvanbruegge** [comment]
On the other hand, uglifyJS does not support ES6 yet, and it is a bit better at minifying than Babili, what is currently doing the job

**Comment by SteveALee** [comment]
Ah I see. But isn't the he critical bit 'some browsers'?

Unless you are targeting an intranet with known browsers I think we still need to target ES5. Sadly. Who knows when we will be able to switch over as there will always be some browser out there with incomplete ES6.

**Comment by jvanbruegge** [comment]
Yeah, I think with ES6 vs ES5 and Babili vs UglifyJS, the difference is neglectable

**Comment by jvanbruegge** [comment]
I run into another problem, code coverage is not working well without babel. Maybe I should add babel to the chain only for the test environment

**Comment by jvanbruegge** [comment]
PR is here: #29

**Comment by SteveALee** [comment]
Only reopening as the README still reads the same as the original issue - ie "piped though babel"

**Comment by jvanbruegge** [comment]
Yeah, this was the only issue that was closed by github automaticly, and it's the one that should not have been :D

**Comment by jvanbruegge** [comment]
Updated the README
