### ISSUE TITLE
Add lint

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#27]
It would be good to add lint, either as a new script as a step in build etc.

The difficulty is deciding what would make a sensible default lint config. It's often a personal or project choice (eg semicolons or not). But we could go for a minimal recommend config.

Currently ESLint is probably the most popular JS linter but currently doesn't support TS. Plus, though an advantage is the wide community resources they may nto make so much sense with TS

TSlint is obviously focussed on TS and is also extensible.

Some ideas to start the discussion

* [tslint-config-standard](https://github.com/blakeembrey/tslint-config-standard)  TSLint version of JS Standard - lightweigth
* [tslint-eslint-rules](https://github.com/buzinas/tslint-eslint-rules) - adding ESLint rules to TSlint - incomplete
* [Microsoft recommended_ruleset.js](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/recommended_ruleset.js) including security and custom rules - extensive

**Comment by jvanbruegge** [comment]
Tslint is already part of the flavor

**Comment by SteveALee** [comment]
Good grief, do it is. How did I not see It?

Sorry for wasting cycles. Senior moment :(
