### ISSUE TITLE
[cycle-scripts-one-fits-all] Add editor config

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#28]
I find [editor config](http://editorconfig.org/) useful to avoid problems due to different editor configs. It's widely supported now. 

The following is an example minimal `.editorconfig` that I find works well on Windows and OS X / Linux and projects when devs use both

```
# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
max_line_length = 100

[*.md]
trim_trailing_whitespace = false
```

**Comment by jvanbruegge** [comment]
Im not sure if this should be part of the flavor. I use edotorconfig myself, but something like that is normally configured by everyone themselves.
I for example hate this dreadful 2 space indentation, because you can't see blocks easy

**Comment by SteveALee** [comment]
I'm not sure either.

* For sole user project it's pointless, as you say
* For project with active community it can save hassle with messed up formats on PRs / commits.
* Agree re 4 spaces but 2 seems to be the most popular.

How do you see the flavour? As an example of good practice or a starter to get you going? If the former then more reason to include it.

How about leaving this ticket open to see if anyone has stronger feelings? Or feel free to close it as a rejected idea.

**Comment by jvanbruegge** [comment]
Flavor is mainly a quickstart. Of course it ships certain best practices in form of config or demo code
I can leave it open

**Comment by jvanbruegge** [comment]
After thinking about it, I really don't think this should be part of the flavor, because it is not related to the config at all, just to the editor you are using
