### ISSUE TITLE
[cycle-scripts-one-fits-all] Why use type rather than interface?

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#34]
Can you explain why you've used `type` rather than `interface`?

I'm still new to TS but the docs do say [interfaces are preferable to types](https://www.typescriptlang.org/docs/handbook/advanced-types.html) unless you need to use tuples or a union?

Thanks

**Comment by jvanbruegge** [comment]
For the source and sink type it is required by cycle, because of internals. I dont think anything else is a type.

**Comment by jvanbruegge** [comment]
Ok checked, there is nothing else :D

**Comment by SteveALee** [comment]
Possibly [these](https://github.com/cyclejs-community/create-cycle-app-flavors/blob/master/packages/cycle-scripts-one-fits-all/template/src/app.tsx#L9-L12)?

**Comment by SteveALee** [comment]
Oh no, not Reducer (btw staltz has returning `| undefined`)

**Comment by jvanbruegge** [comment]
Ok, yeah the state could be an interface.
AFAIK, interfaces are only objects

**Comment by jvanbruegge** [comment]
`undefined` makes only sense if you want to be able to delete children. Thats not the case in the counting app

**Comment by SteveALee** [comment]
Thanks! I grock it now :)
