### ISSUE TITLE
[cycle-scripts-one-fits-all] how to use data-* attributes in JSX

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#36]
I have `<div data-action='speak'>Wibble</div>`
but cyclejs select `sources.DOM.select('[data-action="speak"]')` fails

i see this chrome dev tools
`<div data="[object Object]">Wibble</div>`

Using snabbdom without jsx is fine - 
`div({dataset: {action: 'speak'}}, 'Wibble'),`
and Chrome shows
`<div data-action="speak"">Wibble</div>`
as expected.

Some thoughts:
This may be as the create-cycle-app flavor uses Typescript to do standard React JSX parsing. From what I can determine React CreateElement expects 'data'action: 'speak', the quotes being required due to the semicolon.

`snabbdom-pragma` is being used to map

**Comment by SteveALee** [comment]
@jvanbruegge says 'is a bug, use "dataset-*"'

eg
`<div dataset-action='speak'>Wibble</div>`

**Comment by jvanbruegge** [comment]
Now works with `<div data-action="something" />` as it should

**Comment by SteveALee** [comment]
Thanks. I guess we just run `npm update` as usual even if not ejected?

**Comment by jvanbruegge** [comment]
yes
