### ISSUE TITLE
[one-fits-all flavor] Consider adding prettier

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#38]
At last, [prettier supports TS](https://github.com/prettier/prettier/releases/tag/1.4.0) so we could consider adding it. This issues is here to open a discussion.

This is a bit contentious but it does seem to save a lot of time that would otherwise be spent fiddling about with code layout. Even so, is probably most useful for large teams - not so much small single dev projects.

However, it might be most sensible to leave it out of the flavour and and allow projects to specify it in editor configs if they are interested. I think that might work.

**Comment by jvanbruegge** [comment]
The problem I see is where to put it. You could add an npm script in the package.json, but then that has nothing to to with the flavor and is easy to do yourself. Or you make a git hook, which might not suit everyone

**Comment by SteveALee** [comment]
Thanks for feedback. Agree it's not obvious how to implement.

The more I think about it the more I feel it doesn't really fit. The stated goal of 'one-fits-all' is to "get going" and as a sort of `lint --fix' option prettier is more about good practice for established projects. Sure, if you leave application too late you end up with a lot of 'fix-up' activity, but  we can assume that at some point the project re-assess the need for usch tooling and best practices.

Am closing

**Comment by nickbalestra** [comment]
How you would probably like to use it is for the project code itself, not for the end user (i.e CRA and others also use it in that way)

**Comment by SteveALee** [comment]
@nickbalestra what is 'CRA'?

**Comment by jvanbruegge** [comment]
create-react-app

**Comment by nickbalestra** [comment]
Sorry my bad, CRA -> `create-react-app`
