### ISSUE TITLE
[package:one-fits-all flavour] Thanks and a few questions

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#4]
@jvanbruegge @nickbalestra 

This is a really thorough yet clean flavour and it's great to see CSS, testing and dev/prod all included. I also like your use of a single Interfaces file. Thank you!

I've personally not used the webpack config in JS before but it is easily readable and OK to map to what I know from the .json format. I guess you did it as some plugins etc arte only usable from JS?

I wish I had had this a couple of weeks ago as I spent ages trying to get TS and webpack going. I think it will work for me with a few tweaks

Here's a few questions. Perhaps they might be FAQs?

* Why is it called "TypeScript or ES6" when it seems to be Typescript AND ES6

* Can we document more of the options? There's a lot of awesome knowledge distilled in that config, especially webpack and it would be great to share that. As webpack is JS you could put comments in there or perhaps better the readme. This would help those looking to tweak it.

* Why use Babel as well as TSC? TSC supports ES2015 through target and lib (though confusingly it also has ES6). Or is it required for the JSX-snabdom conversion? 

* Why is the dest empty in ```CopyWebpackPlugin([{ from: 'public', to: '' }])```? I don't see that explained in the docs. Where does it copy too (I'll try in a mo) And shouldn't it be added to .gitignore?

A more general Q for create-cycle-app is can we offer options for flavours with out "eject and edit"? I'd like to keep synced to this but have a few minor changes.

* I don't want JSX - so I can just leave it supported and ignore but would like to simplify and remove
* I use more strict TS compiler options and the ```tslint-microsoft-contrib/recommended_ruleset.js``` config as it is very thorough.
* Rather than ```webpack-dev-server``` I've been using the ```lite-server```` as it uses the excellent browser sync. However this was because weback server can be a real pain which I think you have mostly solved. It doesn't have HMR though but I've not explored this with cyclejs.
* I'm using TypeStyle rather than CSS/SASS
* I was targeting ES5 in TSC. I find this confusing but as I understand it the ES6 option to TSC will mean it might create code that depends on code features and APIs that are not common in browsers or are slow. Thus a shim is probably needed, depending on the source code. Or is that what Bable is doing?
* Am almost certainly going to use ava for testing!

It's probably not worth the complication of trying to support some changes and just support eject - but I do wonder if we could set up paths so some tools (eg TS and TSlint) also pick up extra project configs? I'll explore this some time.

Thank again to both of you for awesome contributions to the cyclejs community

**Comment by jvanbruegge** [comment]
1. Yes, technicly you can use both at the same time
2. The config is using [webpack-blocks](https://github.com/andywer/webpack-blocks) so a lot of documentation can be found there
3. Yes, babel is needed for JSX and that way you can use ES6 too
4. The to is relative to the out dir, so in this case the build folder

General Questions:
1. I use JSX, so i will keep it in, as said, just dont use it
2. I'm in general for more strict rules, you can open an issue, but the tslint.json and tsconfig.json are copied in the project root anyway, so you can overwrite them
3. webpack-dev-server can do everything that lite-server can, plus HMR with JS. I want to look into cyclejs-time-travel to add not only hot reload, but time-travel too
4. As with JSX, you dont have to use it, typestyle is a normal ts lib, so it should work fine
5. the ES6 from TSC is piped through Babel, so you get ES5 in the end too
6. Thats where I dont have a good answer

**Comment by SteveALee** [comment]
> Yes, technicly you can use both at the same time

ah - though template app only has TS. But that's a good thing and so I have no further issue :)

> the tslint.json and tsconfig.json are copied in the project root anyway, so you can overwrite them

Aha, so they are. End of issue! :)

> webpack-dev-server can do everything that lite-server can, plus HMR with JS

Good to hear. Looks like it and the docs have improved immensely since my last very painful experience with it. I was also trying to use multiple browsers and iPad (with 0.0.0.0)

**Comment by jvanbruegge** [comment]
> Aha, so they are. End of issue! :)

You have to leave the awesomeTypescriptLoaderOptions in the tsconfig.json though, thats important

**Comment by SteveALee** [comment]
> The config is using webpack-blocks so a lot of documentation can be found there

Nice!
