### ISSUE TITLE
"Warning: Cannot read property 'flags' of undefined" when building

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#40]
This turns out to be a TSLint issue (it doesn't prefix warnings) and there is an [open issue](https://github.com/palantir/tslint/issues/2876) tracking it.

For me the warning is caused by TSLint rule `no-use-before-declare` but issue indicates it also happens with `no-unused-variable`

**Comment by jvanbruegge** [comment]
This issue was moved to cyclejs-community/one-fits-all#6
