### ISSUE TITLE
Add prettier to repo

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs-community/create-cycle-app-flavors#46]
Add prettier to the repo, maybe even to the flavor itself
If added to the flavor, it's best to just have a `npm run format` command.
The user can then add a git hook if wanted

**Comment by SteveALee** [comment]
Also the VSCode use can install an [extension](https://github.com/prettier/prettier-vscode) that runs prettier on file save.

That's what I use. Just type and save.! A life saver for rubbish typists like myself. :)

To avoid classes with TSLint rules it's best to remove all formating rules from TSLint and let Prettier do it's stuff. There's a [TSLint plugin](https://github.com/alexjoverm/tslint-config-prettier) for that too!
