### ISSUE TITLE
[one-fits-all flavour] A couple depreciated warnings

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app-flavors#8]
npm start leads to the following output on Windows

```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
```

**Comment by jvanbruegge** [comment]
yes, I that is due to webpack blocks using the old syntax. Im currently discussing a change with the main maintainer of webpack-blocks

**Comment by jvanbruegge** [comment]
This issue was moved to cyclejs-community/one-fits-all#7
